# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b0bf629d0a784bf976442d3a56995f2a42322ace38c3297424f251df6161548855db49dceabb4f79ac95e359e877b9ab6ccf51e6e45bbea770df19426212457

test:
  secret_key_base: 66cbc7905c9c1c5d32814d2b8d4d1685707bd4ac96d27a7c3fa00d482dfccd6c59ed875f40b7c05715ace33cbce7d7f1e0b20d7974059b80d0107b60887da8ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
